### ISSUE TITLE
app crashed 

### ISSUE THREAD

**Issue by shahidghafoor00** [byteShaft/TrackBuddy#22]
app get crashed on Qmobile devices.

**Comment by imranhakeem** [comment]
Log Please!

**Comment by fi8er1** [comment]
The issue appears to be for the Qmobile running on 4.2.2 (May appear on other mobiles running the Android version) ActionBarActivity v7 compatibility issue.

**Comment by fi8er1** [comment]
Solved!
Fixed by doing changes in & enabling proguard.
